import img_item1 from "../images/item_sp1.jpg";
export const data = [
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: true,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 20%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 10%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 50%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: true,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: true,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },

  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
  {
    text: "Bộ chăn gối lông cừu Anh giảm giá 30%",
    price: 850.0,
    price__old: 850.0,
    img: img_item1,
    is_ship: true,
    is_sale: false,
  },
];
export const PaginationData = (data, page = 1, limit = 5) => {
  const startIndex = (page - 1) * limit;
  const endIndex = page * limit;
  const result = data.slice(startIndex, endIndex);
  return result;
};
